### PR TITLE
Model into Block

### PR DESCRIPTION
**Pull request by vmasciotta**
I just wrote the model class in order to retrieve data but I'm not so sure about how I injected the model class into the CustomBlock. I mean, in the constructor I specified Tym17\AdminSample\Model\AdminSample and even if this looks correct at first, I don't like it.
In this way the constructor depends on a specific model class (AdminSample) instead of depending on a generic interface.

What do You think?

### CODE REVIEW

**Comment by Tym17** [comment]
It looks fine in my opinion, I remember having troubles getting my models injected in my blocks,  controllers and other places. I had to use ObjectManager like so to get any of my models:
`$this->_config = $objectManager->create('Tym17\Sample\Model\Config');`
Injecting it this way in the constructor: 
`\Magento\Framework\ObjectManagerInterface $objectManager`

However depending on what you are looking to make, I think you can have different approaches, injecting it this way implies it is a sort of singleton. This is probably why you don't like it the way you injected it.

**Comment by Tym17** [comment]
Some classes (if I recall correctly most controllers do) should already have this `ObjectManager` injected by default as private.

**Comment by vmasciotta** [comment]
Thank You for your suggestions, You helped me to understand better this topic.

I spent some time reading about DI in Magento2 in this days because I really didn't know what to think. The official documentation, as always, doesn't explain all the things a developer would need to know. I'm still studying Magento2, that's why I'm so full of dubts.

Anyway in this particular case, just because nobody will probably need to override/replace this model I think that yes, I injected it in the "right way", or at least not in the worse possible way :D (and if someone need to modify methods behaviour, he would use a plugin).

About the way You showed me how to use the Object Manager, it would be very handy and easy to use but it is considered a bad practice. If We pull out something (in this case a model) from the object manager, We are using it as a service locator in the wrong way. We should instead inject the object.

In order to do this correctly way we should:
1. create a file in Tym17/etc/adminhtml/di.xml 
2. modify the CustomBlock.php constructor

More in dept:

Tym17/etc/adminhtml/di.xml should be something like this

``` xml
<?xml version="1.0" ?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="\Tym17\AdminSample\Api\Data\AdminSampleInterface" type="Tym17\AdminSample\Model\AdminSample" />
    <type name="Tym17\AdminSample\Block\Adminhtml\CustomBlock">
        <arguments>
            <argument name="adminSampleModel" xsi:type="object">Tym17\AdminSample\Model\AdminSample</argument>
        </arguments>
        <!--<arguments>
            <argument name="adminSampleModel" xsi:type="object">Tym17\AdminSample\Model\AdminSampleTwo</argument>
        </arguments>-->
    </type>
</config>

```

In **preference** tag we specify that everytime the Object Manager tries to instantiate an AdminSampleInterface, it has to instantiate an AdminSample model:

``` xml
<preference for="\Tym17\AdminSample\Api\Data\AdminSampleInterface" type="Tym17\AdminSample\Model\AdminSample" />
```

If we need more in dept configuration, we can specify that only in Tym17\AdminSample\Block\Adminhtml\CustomBlock constructor, AdminSampleInterface must be an AdminSampleModel:

``` xml
<type name="Tym17\AdminSample\Block\Adminhtml\CustomBlock">
        <arguments>
            <argument name="adminSampleModel" xsi:type="object">Tym17\AdminSample\Model\AdminSample</argument>
        </arguments>
        <!-- if we need to instantiate another model (...\Model\AdminSampleTwo), this should be the way to override the previous one -->
        <!--
        <arguments>
            <argument name="adminSampleModel" xsi:type="object">Tym17\AdminSample\Model\AdminSampleTwo</argument>
        </arguments>-->
    </type>
```

Thus, in the CustomBlock constructor we pass AdminSampleInterface as dependency and the ObjectManager will instantiate the right object, avoiding in this way the service locator problem.

``` php
public function __construct(
        Template\Context $context,
        AdminSampleInterface $adminSampleModel,
        array $data = []
    ) {
        parent::__construct($context, $data);
        $this->_adminSampleModel = $adminSampleModel;
    }

```

In this way, any other developer should be able to configure and to change our settings, and You should easily solve that problems You had when You tried to inject models into blocks and controllers. 

This is what I've learned so far about DI in Magento2, I'm still confused about [injectable and non-injectable](http://devdocs.magento.com/guides/v2.0/extension-dev-guide/depend-inj.html#dep-inj-mod-type-life-mgmt) types and rules.

**Comment by Tym17** [comment]
Yes the official documentation isn't clear sometimes (often in my opinion :P )

You are right, the usage of **objectManager** isn't recommended however it is one of the only ways i found to get a model. I've seen accross Github, samples of plugins that were using it only to get an instance of their model and then would have a sort of secondary `__construct()` function where the model populates itself with the values it have in the database from a given Id value in the URL or returns an error.

Thanks for the explaination on DI, i had trouble while understanding how Magento2's XML files works since the doc is not that populated. And about those injectables and non-injectables i guess that every model that relies on doing general operations (such as a singleton or the model you created) could be injectables otherwise models requiring special values in order to work or representing values such as an order or so should not be injectable which sounds normal since you can't really pass a particular parameter while creating it. 
This goes back to the process i seen on Github using the _objectManager_ to get the model structure then populating it but this rely on the _objectManager_ which in theory should not be used.

**Pull request merged**
